### ISSUE TITLE
Descriptions of the GELR2R datasets

### ISSUE THREAD

**Issue by honghd16** [CSir1996/VLN-GELA#4]
Hi Yibo,

Thanks for your great work!
Could I get some clarification on the format of the GELR2R annotations for the landmarks?
It seems that the "landmark_bbox_coords" appears unconventional, either not pixel-based or normalized to [0,1], with x-values ranging from 0 to 2 and y-values from 0 to 1, which makes me confused. Also, the paper says the format of the bounding box is [x,y,w,h], but I found it more like [x1,y1, x2, y2] ?
Another problem is how can I get the landmark images. The landmark bounding boxes are based on the panorama of the Matterport3D datasets. However, in most VLN works, they use 36 discrete views to represent that panorama. Is it also discrete views in the GELR2R annotations or some tools are used to generate the panorama for the bounding boxes?

Cheers

**Comment by CSir1996** [comment]
Yeah, in the "landmark_bbox_coords", x-values are normalized to [0,2] and y-values are normalized to [0,1] because the pano images are 2048*1024 captured from the MP3D simulator. We generated panos based on a jupyter notebook (https://gist.github.com/ronghanghu/d250f3a997135c667b114674fc12edae) from the great work Speaker-Follower.

**Comment by honghd16** [comment]
Thank you so much, Yibo. This is really helpful. Happy New Year!

**Comment by honghd16** [comment]
Hi Yibo,
I tried the panos generated by the jupyter notebook you provided. It concat 36 discrete views to generate a (480, 2880) pano image. How to get the 2048*1024 panos you use? Because it seems both 1024 and 2048 are not divisible by 36.
Thanks!
